### ISSUE TITLE
Lack of prompts

### ISSUE THREAD

**Issue by Ririio** [dadolhay/dadolhay-ssg#2]
The user needs an indication when they do an incorrect procedure. For example, the program should prompt the user for the wrong directory or file names. This ensures the user spots the problem immediately

**Comment by Ririio** [comment]
When a user use the input flag to an non-existent file or folder, it doesn't provide them with any information for what the problem with their command was i.e.,

typing **node ./ssg.js --input ./input**  simply doesn't prompt the user that the process failed. This is a problem, because there's no indication of whether the process succeeded or not

**Comment by dadolhay** [comment]
Okay, I have written a protection against this
