### ISSUE TITLE
Avoid cluttering the main directory

### ISSUE THREAD

**Issue by Ririio** [dadolhay/dadolhay-ssg#5]
I noticed that when using the output, the user creates a new folder for each different instance of output. The problem with this is that the user can keep on creating new directories, and it will clutter the main one. I suggest to either delete the old output directory and its content, or create a separate folder that contains all existing output directories

**Comment by dadolhay** [comment]
The output can be anywhere, not only inside this project.

The code is only supposed to follow the user's instructions. If they specify the output, then that's where they expect it to be. Removing the old folder is outside the scope of the project
